server:
  port: 7777
  origin: 'http://localhost:3000'

db:
  host: ''
  type: ''
  port: 5432
  database: 'truthy'
  synchronize: false

jwt:
  expiresIn: 86400
  refreshExpiresIn: 604800
  cookieExpiresIn: 604800

app:
  name: 'Truthy'
  version: 'v0.1'
  description: 'Official Truthy API'
  appUrl: 'https://truthy.onrender.com/'
  frontendUrl: https://service-sync-frontend.vercel.app
  frontendUrl2: https://service-sync-cpanel.netlify.app

mail:
  host: 'smtp.gmail.com'
  port: 465
  user: 'servicesyncplatform@gmail.com'
  pass: 'sbev xkme jgit ntel'
  from: 'Service-Sync'
  fromMail: 'servicesyncplatform@gmail.com'
  preview: true
  secure: true
  # ignoreTLS: true
  queueName: 'truthy-mail'

queue:
  driver: 'redis'
  host: 'localhost'
  port: 6379
  db: ''
  password: ''
  username: ''

throttle:
  global:
    ttl: 60
    limit: 60
  login:
    prefix: 'login_fail_throttle'
    limit: 5
    duration: 2592000
    blockDuration: 3000
