server:
  port: 7777
  origin: 'http://localhost:3000'

db:
  host: 'postgresql://postgres:qmlhQDpyoXeouPXEhXeCduDnElWlVhmv@autorack.proxy.rlwy.net:20498/railway'
  type: 'postgres'
  port: 5432
  database: 'railway'
  synchronize: false

jwt:
  expiresIn: 86400
  refreshExpiresIn: 604800
  cookieExpiresIn: 604800

app:
  name: 'Truthy'
  version: 'v0.1'
  description: 'Official Truthy API'
  appUrl: 'https://truthy-backend.herokuapp.com/'
  frontendUrl: 'http://localhost:3000'

mail:
  host: ''
  port: 2525
  user: ''
  pass: ''
  from: 'truthycms'
  fromMail: 'truthycms@gmail.com'
  preview: true
  secure: false
  ignoreTLS: true
  queueName: 'truthy-mail'

queue:
  driver: 'redis'
  host: 'redis://default:MRMhThdoMupZjkZNuNWUvXwCpvRsRzvw@autorack.proxy.rlwy.net:36416'
  port: 6379
  db: ''
  password: ''
  username: ''

throttle:
  global:
    ttl: 60
    limit: 60
  login:
    prefix: 'login_fail_throttle'
    limit: 5
    duration: 2592000
    blockDuration: 3000
